# Generated by Django 6.1.1 on 2026-10-03 13:48
# Dependensi pada tenant sengaja `__latest__`, bukan nama migrasi tertentu:
#  * nama migrasi tenant berbeda di tiap project, dan
#  * `__first__` GAGAL bila Member/Association dibuat di migrasi tenant yang bukan pertama
#    (ValueError: Related model 'tenant.member' cannot be resolved).

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '__latest__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_id', models.BigIntegerField()),
                ('log_seq', models.IntegerField(null=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('sha256', models.BinaryField(max_length=32, null=True)),
                ('upload_key', models.CharField(max_length=255, unique=True)),
                ('media_key', models.CharField(max_length=255, unique=True)),
                ('multipart_upload_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'menunggu unggahan'), ('processing', 'sedang diverifikasi'), ('ready', 'siap (tercatat di ledger)'), ('failed', 'gagal / kedaluwarsa'), ('erased', 'dihapus (hash di ledger tetap)')], default='pending', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_since', models.DateTimeField(null=True)),
                ('finalized_at', models.DateTimeField(null=True)),
                ('last_verified_at', models.DateTimeField(null=True)),
                ('erased_at', models.DateTimeField(null=True)),
                ('association', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant.association')),
                ('erased_by', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant.member')),
                ('uploaded_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant.member')),
            ],
            options={
                'indexes': [models.Index(fields=['collection_id', 'status'], name='media_coll_status_idx'), models.Index(fields=['status', 'created_at'], name='media_status_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('log_seq__isnull', False)), fields=('collection_id', 'log_seq'), name='media_one_per_log'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(('sha256__isnull', False), ('log_seq__isnull', False)), _connector='OR'), name='media_ready_has_proof')],
            },
        ),
    ]
