# Generated by Django 6.1.1 on 2026-10-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='tenant_cert_member__f1816c_idx',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
