# Generated by Django 6.1.1 on 2026-10-02 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='CREATED', max_length=50)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('assigner', models.ForeignKey(blank=True, help_text='Manusia (User) yang membuat atau mendaftarkan aset ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collections', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='tenant.association')),
                ('collection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vault.collectiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm', models.CharField(default='ed25519', max_length=30)),
                ('payload_version', models.PositiveIntegerField(default=1)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='tenant.certificate')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='vault.collection')),
            ],
            options={
                'indexes': [models.Index(fields=['collection', '-signed_at'], name='vault_colle_collect_bb4a64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tenant.association')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['association', '-created_at'], name='vault_entry_associa_4f7cbe_idx'), models.Index(fields=['occurred_at'], name='vault_entry_occurre_20adf0_idx')],
            },
        ),
    ]
