# Generated by Django 6.1.1 on 2026-10-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='assigner',
        ),
        migrations.AddField(
            model_name='entry',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='tenant.member'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='tenant.association'),
        ),
    ]
