# Generated by Django 6.1.1 on 2026-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_seed_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(unique=True)),
                ('label', models.CharField()),
            ],
            options={
                'db_table': 'ledger_actions',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionRule',
            fields=[
                ('pk', models.CompositePrimaryKey('action_id', 'tool_kind_id', 'target_kind_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('target_access', models.SmallIntegerField(choices=[(1, 'pemilik sasaran'), (2, 'siapa pun, saat sasaran sedang dikirim (cap pos)'), (3, 'siapa pun, sasaran aktif (buku tamu)')])),
            ],
            options={
                'db_table': 'ledger_action_rules',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('log_count', models.BigIntegerField()),
                ('merkle_root', models.BinaryField()),
                ('prev_block_hash', models.BinaryField()),
                ('block_hash', models.BinaryField()),
                ('sealed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_blocks',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_no', models.CharField(max_length=100)),
                ('state', models.SmallIntegerField(choices=[(1, 'aktif'), (2, 'dalam pengiriman')])),
                ('last_seq', models.IntegerField()),
                ('tool_uses', models.IntegerField()),
                ('target_acts', models.IntegerField()),
                ('last_hash', models.BinaryField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_collections',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('supply', models.IntegerField()),
                ('minted_count', models.IntegerField()),
                ('metadata', models.JSONField()),
                ('content_hash', models.BinaryField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_entries',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('pk', models.CompositePrimaryKey('owner_id', 'collection_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ledger_holdings',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(unique=True)),
                ('label', models.CharField()),
                ('max_as_tool', models.IntegerField(null=True)),
                ('max_as_target', models.IntegerField(null=True)),
                ('restricted', models.BooleanField()),
            ],
            options={
                'db_table': 'ledger_kinds',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KindIssuer',
            fields=[
                ('pk', models.CompositePrimaryKey('kind_id', 'association_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ledger_kind_issuers',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('pk', models.CompositePrimaryKey('collection_id', 'seq', blank=True, editable=False, primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('event_type', models.SmallIntegerField(choices=[(1, 'lahir'), (2, 'dikirim'), (3, 'diterima'), (4, 'dipakai (aksi tunggal, atau sisi ALAT dari aksi antar-item)'), (5, 'pengiriman dibatalkan pengirim'), (7, 'dikenai aksi (sisi SASARAN dari aksi antar-item)')])),
                ('target_id', models.BigIntegerField(null=True)),
                ('target_seq', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
                ('hash', models.BinaryField()),
                ('content_hash', models.BinaryField(null=True)),
                ('payload', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'ledger_logs',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferToken',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ledger_transfer_tokens',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
