# Generated by Django 6.1.1 on 2026-10-08 15:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_transaction_queue'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Judul atau label singkat dari konten', max_length=255)),
                ('format', models.CharField(choices=[('plain', 'Plain Text'), ('markdown', 'Markdown'), ('html', 'HTML'), ('json', 'JSON')], default='plain', max_length=20)),
                ('body', models.TextField(help_text='Isi konten teks utama')),
                ('excerpt', models.CharField(blank=True, help_text='Preview singkat untuk list view', max_length=255)),
                ('content_hash', models.CharField(help_text='SHA256 hex dari kolom body', max_length=64)),
                ('char_count', models.PositiveIntegerField(default=0, help_text='Jumlah karakter untuk fast query/lookup')),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='ledger.collection')),
                ('created_by_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', to='tenant.member')),
            ],
            options={
                'db_table': 'ledger_contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_hash'], name='ledger_cont_conten_2b2c3e_idx'), models.Index(fields=['status'], name='ledger_cont_status_3c2c3e_idx')],
            },
        ),
    ]
