# Generated by Django 6.1.1 on 2026-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_per_entry_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, help_text='Isi konten teks utama'),
        ),
    ]
