"""
Django settings for snailstamp project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
environ.Env.read_env(os.path.join(BASE_DIR.parent.parent.parent, '.env'))
env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jb(531ds%&u$*c178!0m^y%9%ty(hkgalpgxrolj(30s-_g%b$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps FIRST (tenant must be before auth)
    'snailstamp.apps.tenant',
    'snailstamp.apps.ledger',

    # auth after tenant (custom user model)
    'django.contrib.auth',

    # third party (depends on auth)
    'guardian',
    'organizations',
    'rest_framework',
    'drf_spectacular',

    # admin last
    'django.contrib.admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'snailstamp.core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snailstamp.core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Storage Configuration
# https://docs.djangoproject.com/en/6.1/topics/files/

# Default storage backend (local for development, S3 for production)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent.parent.parent / 'media'

# S3 Configuration (for production)
# Set USE_S3=True in .env to enable S3 storage
USE_S3 = env.bool('USE_S3', default=False)

if USE_S3:
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        'OPTIONS': {
            'bucket_name': env('AWS_STORAGE_BUCKET_NAME'),
            'region_name': env('AWS_S3_REGION_NAME', default='us-east-1'),
            'custom_domain': env('AWS_S3_CUSTOM_DOMAIN', default=None),
            'file_overwrite': False,  # Content-addressable: don't overwrite
            'default_acl': 'private',
        },
    }
    MEDIA_URL = f"https://{env('AWS_STORAGE_BUCKET_NAME')}.s3.{env('AWS_S3_REGION_NAME', default='us-east-1')}.amazonaws.com/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

AUTH_USER_MODEL='tenant.User'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend'
)


# DRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ("v1",),
    "VERSION_PARAM": "version",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "EXCEPTION_HANDLER": "snailstamp.api.exceptions.exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SnailStamp API",
    "DESCRIPTION": "Versioned REST API for SnailStamp associations and the tamper-evident item ledger.",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Ledger integrity (lihat BLOCK_SIGNING.md)
LEDGER_REQUIRE_BLOCK_SIGNATURES = env.bool('LEDGER_REQUIRE_BLOCK_SIGNATURES', default=True)
LEDGER_ANCHOR_INTERVAL = env.int('LEDGER_ANCHOR_INTERVAL', default=100)
LEDGER_ANCHOR_BACKENDS = []
if env('LEDGER_ANCHOR_FILE', default=''):
    LEDGER_ANCHOR_BACKENDS.append({
        'NAME': 'file',
        'BACKEND': 'snailstamp.apps.ledger.anchors.FileAnchorBackend',
        'OPTIONS': {'path': env('LEDGER_ANCHOR_FILE')},
    })
if env('LEDGER_ANCHOR_URL', default=''):
    LEDGER_ANCHOR_BACKENDS.append({
        'NAME': 'http',
        'BACKEND': 'snailstamp.apps.ledger.anchors.HttpAnchorBackend',
        'OPTIONS': {'url': env('LEDGER_ANCHOR_URL'), 'token_env': 'LEDGER_ANCHOR_TOKEN'},
    })

# Multi-sealer: produksi sebaiknya 2 signature dari 2 region (lihat `manage.py check --deploy`)
BLOCK_SIGNATURE_THRESHOLD = env.int('BLOCK_SIGNATURE_THRESHOLD', default=1)
LEDGER_SEALER_MIN_REGIONS = env.int('LEDGER_SEALER_MIN_REGIONS', default=1)
LEDGER_SEALER_REGION = env('LEDGER_SEALER_REGION', default='')

# Watchtower (manage.py watch_ledger)
LEDGER_MAX_BLOCK_AGE = env.int('LEDGER_MAX_BLOCK_AGE', default=60)       # detik
LEDGER_MAX_COSIGN_LAG = env.int('LEDGER_MAX_COSIGN_LAG', default=300)    # detik
LEDGER_WITNESS_INTERVAL = env.int('LEDGER_WITNESS_INTERVAL', default=1)
LEDGER_ALERT_WEBHOOK = env('LEDGER_ALERT_WEBHOOK', default='')
LEDGER_WITNESS_BACKENDS = []
if env('LEDGER_WITNESS_FILE', default=''):
    LEDGER_WITNESS_BACKENDS.append({
        'NAME': f"witness-{LEDGER_SEALER_REGION or 'local'}",
        'BACKEND': 'snailstamp.apps.ledger.anchors.FileAnchorBackend',
        'OPTIONS': {'path': env('LEDGER_WITNESS_FILE')},
    })

# Optional transaction queue. Limit counts enqueues by association over a rolling window;
# set limit to 0 to disable throttling. Existing synchronous services are unaffected.
LEDGER_QUEUE_RATE_LIMIT = env.int('LEDGER_QUEUE_RATE_LIMIT', default=60)
LEDGER_QUEUE_RATE_PERIOD_SECONDS = env.int('LEDGER_QUEUE_RATE_PERIOD_SECONDS', default=60)
LEDGER_QUEUE_BATCH_SIZE = env.int('LEDGER_QUEUE_BATCH_SIZE', default=100)
LEDGER_MEMBER_CHECK = 'snailstamp.apps.tenant.ledger_authz.member_can_act'

# Celery uses Redis for delivery/wakeup; queued transaction payloads remain in PostgreSQL.
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_TASK_DEFAULT_QUEUE = 'ledger_transactions'
CELERY_TASK_DEFAULT_EXCHANGE = 'ledger_transactions'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'ledger_transactions'
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_DEFAULT_DELIVERY_MODE = 'persistent'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 3600}

# Recovery sweep covers a broker outage between the DB commit and task publication.
CELERY_BEAT_SCHEDULE = {
    'ledger-queue-recovery-sweep': {
        'task': 'snailstamp.ledger.process_queue_batch',
        'schedule': 5.0,
    },
}
